openapi: 3.0.3
info:
  title: yna admin bff spec
  description: admin
  version: 0.0.1
paths: {}

components:
  schemas:
    Site:
      type: object
      properties:
        siteId:
          type: string
          example: 'xxxx'
        title:
          type: string
          example: 'todo'
        priority:
          type: integer
          example: 1
      required:
        - siteId
        - title
        - priority

    SiteList:
      allOf:
        - $ref: '../../components/schemas.yaml/#/components/schemas/Pager'
        - type: object
          properties:
            list:
              type: array
              items:
                $ref: '#/components/schemas/Site'
          required:
            - list
