openapi: 3.0.3
info:
  title: oas common schemas
  description: common schemas
  version: 0.0.1
paths: {}

components:
  schemas:
    Pager:
      type: object
      properties:
        count:
          type: integer
          example: 100
        currentPage:
          type: integer
          example: 1
      required:
        - count
        - currentPage

    Timestamp:
      type: object
      properties:
        openedAt:
          type: integer
        createdAt:
          type: integer
        modifiedAt:
          type: integer
