openapi: 3.0.3
info:
  title: oas common schemas
  description: common schemas
  version: 0.0.1
paths: { }

components:
  schemas:
    Count:
      type: object
      properties:
        count:
          type: integer
          example: 100

    CurrentPage:
      type: object
      properties:
        currentPage:
          type: integer
          example: 1

    Pager:
      allOf:
        - $ref: '#/components/schemas/Count'
        - $ref: '#/components/schemas/CurrentPage'

    SpaceId:
      type: object
      properties:
        siteId:
          type: string
          example: 'xxxx'

    Title:
      type: object
      properties:
        title:
          type: string
          example: 'todo'

    Priority:
      type: object
      properties:
        priority:
          type: integer
          example: 1
