openapi: 3.0.3
info:
  title: yna admin bff spec
  description: admin
  version: 0.0.1

servers:
  - url: /v1

tags:
  - name: system
    description: system relation api
  - name: site
    description: site relation api

paths:
  # system
  /ping:
    $ref: './paths/pings.yaml#/ping'

  # site
  /sites:
    $ref: './paths/sites.yaml#/sites'

components:
  schemas:
    # common
    Pager:
      $ref: '../components/schemas.yaml#/components/schemas/Pager'

    # site
    Site:
      $ref: './components/sites.yaml#/components/schemas/Site'
    SiteList:
      $ref: './components/sites.yaml#/components/schemas/SiteList'